[postgres.user]
name = "postgres_user"
password = "your_secure_password"

[postgres.database]
host = "localhost"
port = 5432
name = "your_database_name"
flush_every = 100

[paths]
curricula = "path/to/your/curricula/files"
alembic = "alembic.ini"